#[derive(Debug, Clone, PartialEq)]
pub struct WorkflowExecutionMachine {
    workflow_id: String,
    run_id: String,
    attempt_id: String,
    title: String,
    step_count: usize,
    step_resolutions: Vec<WorkflowStepResolution>,
    approval_checks: Vec<WorkflowApprovalCheck>,
    policy_decisions: Vec<Option<super::policy_manifest::PolicyDecisionReport>>,
    approval_store: InMemoryApprovalStore,
    persistent_approval_store: Option<FileApprovalStore>,
    approval_requests: Vec<ApprovalRequest>,
    identity_check_report: Option<IdentityCheckReport>,
    no_duplicate_tui_report: Option<NoDuplicateTuiReport>,
    architecture_invariants_report: Option<ArchitectureInvariantReport>,
    ownership_scan_report: Option<OwnershipScanReport>,
    root_seed_registry_report: Option<RegistryLoadReport>,
    build_check_report: Option<build_check::BuildCheckReport>,
    build_check_repo_root: Option<PathBuf>,
    donor_status_report: Option<DonorStatusReport>,
    build_check_cargo_program: Option<PathBuf>,
    tui_pty_gate_result: Option<TuiPtyGateResult>,
    cursor: usize,
    started_step_count: usize,
    completed_step_count: usize,
    waiting_approval_step_count: usize,
    blocked_step_count: usize,
    started: bool,
    finished: bool,
    cancelled_reason: Option<String>,
    failed_reason: Option<String>,
    current_step_index: Option<usize>,
    current_step_resolution: Option<WorkflowStepResolution>,
    current_step_lifecycle: Option<WorkflowStepLifecycle>,
    state_trace: Vec<WorkflowExecutionState>,
    events: Vec<WorkflowExecutionEvent>,
}

