pub mod approval_lifecycle;
pub mod approval_readiness;
pub mod approval_store;
pub mod architecture_invariants;
#[allow(clippy::duplicate_mod)]
pub mod build_check;
pub mod build_readiness;
pub mod capability_manifest;
pub mod capability_registry;
pub mod completion_lock;
pub mod docs_maintenance;
pub mod donor_domain_contract;
pub mod donor_status;
pub mod enforcement_doctor;
pub mod enforcement_level;
pub mod evidence_v2;
pub mod identity_check;
pub mod kind_registry;
pub mod memory_doctor;
pub mod no_duplicate_tui;
pub mod ownership_scan;
pub mod policy_manifest;
pub mod policy_registry;
pub mod registry;
pub mod registry_diagnostics;
pub mod root_feature_catalog;
pub mod root_feature_conversion;
pub mod schema_envelope;
pub mod semantic_anchor;
pub mod session_artifacts;
pub mod session_closeout;
pub mod session_doctor;
pub mod slice_ledger;
pub mod surface_doctor;
pub mod surface_manifest;
pub mod surface_readiness;
pub mod surface_registry;
pub mod vac_init_approval_binding;
pub mod vac_init_autopilot_scheduler;
pub mod vac_init_cli_runtime;
pub mod vac_init_command_gate;
pub mod vac_init_doctor_release;
pub mod vac_init_durable_stores;
pub mod vac_init_evidence_chain;
pub mod vac_init_evidence_writer;
pub mod vac_init_fixture_security_regression;
pub mod vac_init_lifecycle;
pub mod vac_init_live_scanner_policy;
pub mod vac_init_live_stores;
pub mod vac_init_manifest_contract;
pub mod vac_init_memory_governance;
pub mod vac_init_migration_runtime;
pub mod vac_init_ownership_scanner;
pub mod vac_init_patch_guard;
pub mod vac_init_policy_evaluator;
pub mod vac_init_production_rc;
pub mod vac_init_registry_strictness;
pub mod vac_init_registry_validator;
pub mod vac_init_risk_policy;
pub mod vac_init_runtime_bridge;
pub mod vac_init_runtime_enforcement;
pub mod vac_init_safe_rationale;
pub mod vac_init_scanner_policy_hardening;
pub mod vac_init_semantic_plan;
pub mod vac_init_tui_real_data;
pub mod workflow_manifest;
pub mod workflow_registry;
pub mod workflow_runner;

pub use approval_readiness::ApprovalReadinessReport;
pub use approval_readiness::load_approval_readiness_report;
pub use approval_store::FileApprovalStore;
pub use architecture_invariants::ArchitectureInvariantCheck;
pub use architecture_invariants::ArchitectureInvariantReport;
pub use architecture_invariants::ArchitectureInvariantStatus;
pub use architecture_invariants::load_architecture_invariant_report;
pub use build_check::BuildCheckReport;
pub use build_check::BuildCheckRequest;
pub use build_check::run_build_check;
pub use build_readiness::BuildReadinessReport;
pub use build_readiness::load_build_readiness_report;
pub use docs_maintenance::DocsMaintenanceIssue;
pub use docs_maintenance::DocsMaintenanceReport;
pub use docs_maintenance::DocsMaintenanceSeverity;
pub use docs_maintenance::load_docs_maintenance_report;
pub use donor_domain_contract::DonorDomainContract;
pub use donor_domain_contract::DonorDomainContractFinding;
pub use donor_domain_contract::DonorDomainContractReport;
pub use donor_domain_contract::DonorDomainContractSeverity;
pub use donor_domain_contract::DonorDomainExecutionStance;
pub use donor_domain_contract::load_donor_domain_contract_report;
pub use donor_status::DonorStatusEntry;
pub use donor_status::DonorStatusFailure;
pub use donor_status::DonorStatusReport;
pub use donor_status::load_donor_status_report;
pub use enforcement_doctor::EnforcementDoctorReport;
pub use enforcement_doctor::load_enforcement_doctor_report;
pub use enforcement_level::EnforcementClaimScope;
pub use enforcement_level::EnforcementLevel;
pub use enforcement_level::EnforcementObserved;
pub use enforcement_level::EnforcementSandboxObserved;
pub use enforcement_level::EnforcementStatusReport;
pub use enforcement_level::load_enforcement_status_report;
pub use evidence_v2::EvidenceSigner as EvidenceV2Signer;
pub use evidence_v2::EvidenceStore as EvidenceV2Store;
pub use evidence_v2::EvidenceV2;
pub use evidence_v2::EvidenceV2DoctorReport;
pub use evidence_v2::EvidenceV2ResignReport;
pub use evidence_v2::GitRefEvidenceStore as EvidenceV2GitRefStore;
pub use evidence_v2::MerkleRoot as EvidenceV2MerkleRoot;
pub use evidence_v2::XrefMarker as EvidenceV2XrefMarker;
pub use evidence_v2::load_evidence_v2_doctor_report;
pub use identity_check::IdentityCheckFinding;
pub use identity_check::IdentityCheckReport;
pub use identity_check::load_identity_check_report;
pub use kind_registry::KIND_REGISTRY;
pub use kind_registry::KindRegistry;
pub use kind_registry::KindRegistryEntry;
pub use kind_registry::KindRegistryError;
pub use kind_registry::ManifestKindDomain;
pub use kind_registry::ManifestKindStance;
pub use kind_registry::VacManifestKind;
pub use kind_registry::canonical_kind_names;
pub use kind_registry::is_known_kind;
pub use kind_registry::kind_registry_entry;
pub use kind_registry::legacy_kind_names;
pub use kind_registry::validate_manifest_kind;
pub use memory_doctor::MemoryDoctorReport;
pub use memory_doctor::load_memory_doctor_report;
pub use schema_envelope::SUPPORTED_SCHEMA_VERSION;
pub use schema_envelope::SchemaEnvelope;
pub use schema_envelope::SchemaEnvelopeError;
pub use schema_envelope::SchemaEnvelopeFields;
pub use schema_envelope::extract_schema_envelope_fields;
pub use schema_envelope::parse_schema_envelope_from_yaml_str;
pub use schema_envelope::parse_schema_envelope_str;
pub use schema_envelope::validate_dotted_manifest_id;
pub use schema_envelope::validate_manifest_id;
pub use schema_envelope::validate_schema_envelope;

pub use vac_init_autopilot_scheduler::AutopilotActionReport as VacInitAutopilotActionReport;
pub use vac_init_autopilot_scheduler::AutopilotJobRecord as VacInitAutopilotJobRecord;
pub use vac_init_autopilot_scheduler::AutopilotSchedulerRuntimeReport as VacInitAutopilotSchedulerRuntimeReport;
pub use vac_init_autopilot_scheduler::execute_autopilot_action as execute_vac_init_autopilot_action;
pub use vac_init_autopilot_scheduler::refresh_autopilot_scheduler_status as refresh_vac_init_autopilot_scheduler_status;
pub use vac_init_evidence_writer::LiveEvidenceWriteRequest as VacInitLiveEvidenceWriteRequest;
pub use vac_init_evidence_writer::LiveEvidenceWriteResult as VacInitLiveEvidenceWriteResult;
pub use vac_init_evidence_writer::write_live_evidence_and_trajectory as write_vac_init_live_evidence_and_trajectory;
pub use vac_init_lifecycle::InitLifecycleError;
pub use vac_init_lifecycle::VacInitLifecycleState;
pub use vac_init_lifecycle::VacInitStateRecord;
pub use vac_init_lifecycle::advance_init_state;
pub use vac_init_lifecycle::allowed_commands_for_state;
pub use vac_init_lifecycle::can_transition;
pub use vac_init_live_scanner_policy::build_live_risk_findings as build_vac_init_live_risk_findings;
pub use vac_init_live_scanner_policy::build_live_scanner_report_files as build_vac_init_live_scanner_report_files;
pub use vac_init_live_scanner_policy::build_live_scanner_reports as build_vac_init_live_scanner_reports;
pub use vac_init_live_scanner_policy::build_live_source_inventory as build_vac_init_live_source_inventory;
pub use vac_init_live_scanner_policy::render_policy_inference_report_yaml as render_vac_init_policy_inference_report_yaml;
pub use vac_init_live_scanner_policy::render_risk_findings_yaml as render_vac_init_risk_findings_yaml;
pub use vac_init_live_scanner_policy::render_source_inventory_yaml as render_vac_init_source_inventory_yaml;
pub use vac_init_live_stores::LiveStoreWriteResult as VacInitLiveStoreWriteResult;
pub use vac_init_live_stores::read_vac_init_store_record;
pub use vac_init_live_stores::write_vac_init_store_record_atomic;
pub use vac_init_manifest_contract::CapabilityLifecycleStatus as VacInitCapabilityLifecycleStatus;
pub use vac_init_manifest_contract::CapabilityManifestContract;
pub use vac_init_manifest_contract::ManifestValidationReport as VacInitManifestValidationReport;
pub use vac_init_manifest_contract::PolicyDecision as VacInitPolicyDecision;
pub use vac_init_manifest_contract::StructuredValidationCommand as VacInitStructuredValidationCommand;
pub use vac_init_manifest_contract::SurfaceManifestContract as VacInitSurfaceManifestContract;
pub use vac_init_manifest_contract::WorkflowManifestContract as VacInitWorkflowManifestContract;
pub use vac_init_manifest_contract::merge_policy_decisions as merge_vac_init_policy_decisions;
pub use vac_init_manifest_contract::validate_capability_contract as validate_vac_init_capability_contract;
pub use vac_init_manifest_contract::validate_policy_contract as validate_vac_init_policy_contract;
pub use vac_init_manifest_contract::validate_surface_contract as validate_vac_init_surface_contract;
pub use vac_init_manifest_contract::validate_workflow_contract as validate_vac_init_workflow_contract;
pub use vac_init_ownership_scanner::OwnershipCoverageStatus as VacInitOwnershipCoverageStatus;
pub use vac_init_ownership_scanner::OwnershipReport as VacInitOwnershipReport;
pub use vac_init_ownership_scanner::OwnershipTargetPattern as VacInitOwnershipTargetPattern;
pub use vac_init_ownership_scanner::QuarantineLevel as VacInitQuarantineLevel;
pub use vac_init_ownership_scanner::SourceInventoryReport as VacInitSourceInventoryReport;
pub use vac_init_ownership_scanner::build_ownership_report as build_vac_init_ownership_report;
pub use vac_init_ownership_scanner::build_source_inventory_from_paths as build_vac_init_source_inventory_from_paths;
pub use vac_init_registry_strictness::StrictnessDiagnostic as VacInitStrictnessDiagnostic;
pub use vac_init_registry_strictness::StrictnessSeverity as VacInitStrictnessSeverity;
pub use vac_init_registry_strictness::StructuredCommandShape as VacInitStrictStructuredCommandShape;
pub use vac_init_registry_strictness::validate_kind_strict as validate_vac_init_kind_strict;
pub use vac_init_registry_strictness::validate_structured_command_shape as validate_vac_init_structured_command_shape;
pub use vac_init_registry_validator::RegistryManifestRecord as VacInitRegistryManifestRecord;
pub use vac_init_registry_validator::RegistryValidationReport as VacInitRegistryValidationReport;
pub use vac_init_registry_validator::RegistryValidatorDiagnostic as VacInitRegistryValidatorDiagnostic;
pub use vac_init_registry_validator::validate_registry_path as validate_vac_init_registry_path;
pub use vac_init_registry_validator::validate_registry_records as validate_vac_init_registry_records;
pub use vac_init_registry_validator::validate_registry_yaml_documents as validate_vac_init_registry_yaml_documents;

pub use vac_init_approval_binding::ApprovalReplayStore as VacInitApprovalReplayStore;
pub use vac_init_approval_binding::ApprovalRequestRecord as VacInitApprovalRequestRecord;
pub use vac_init_approval_binding::ApprovalResponseSignature as VacInitApprovalResponseSignature;
pub use vac_init_approval_binding::ApprovalSignaturePolicy as VacInitApprovalSignaturePolicy;
pub use vac_init_approval_binding::approval_signature_payload as vac_init_approval_signature_payload;
pub use vac_init_approval_binding::consume_approval as consume_vac_init_approval;
pub use vac_init_approval_binding::validate_approval_binding as validate_vac_init_approval_binding;
pub use vac_init_approval_binding::validate_approval_binding_with_signature_policy as validate_vac_init_approval_binding_with_signature_policy;
pub use vac_init_approval_binding::verify_approval_ed25519_signature as verify_vac_init_approval_ed25519_signature;
pub use vac_init_cli_runtime::CliExitClass as VacInitCliExitClass;
pub use vac_init_cli_runtime::CliRuntimeCommandKind as VacInitCliRuntimeCommandKind;
pub use vac_init_cli_runtime::DoctorTaxonomyContract as VacInitDoctorTaxonomyContract;
pub use vac_init_cli_runtime::InitCliMode as VacInitCliMode;
pub use vac_init_cli_runtime::PlanValidateCliContract as VacInitPlanValidateCliContract;
pub use vac_init_cli_runtime::WhyCliTarget as VacInitWhyCliTarget;
pub use vac_init_cli_runtime::parse_why_target as parse_vac_init_why_target;
pub use vac_init_cli_runtime::resolve_init_mode as resolve_vac_init_mode;
pub use vac_init_command_gate::CommandGateDecision as VacInitCommandGateDecision;
pub use vac_init_command_gate::CommandGateReport as VacInitCommandGateReport;
pub use vac_init_command_gate::CommandRunnerRegistry as VacInitCommandRunnerRegistry;
pub use vac_init_command_gate::StructuredCommand as VacInitStructuredCommandGateCommand;
pub use vac_init_command_gate::evaluate_structured_command as evaluate_vac_init_structured_command;
pub use vac_init_evidence_chain::EvidenceRecord as VacInitEvidenceRecord;
pub use vac_init_evidence_chain::EvidenceSignatureEnvelope as VacInitEvidenceSignatureEnvelope;
pub use vac_init_evidence_chain::compute_evidence_self_hash as compute_vac_init_evidence_self_hash;
pub use vac_init_evidence_chain::evidence_signature_payload as vac_init_evidence_signature_payload;
pub use vac_init_evidence_chain::finalize_evidence_record as finalize_vac_init_evidence_record;
pub use vac_init_evidence_chain::sha256_hex as vac_init_sha256_hex;
pub use vac_init_evidence_chain::verify_evidence_chain as verify_vac_init_evidence_chain;
pub use vac_init_evidence_chain::verify_evidence_ed25519_signature as verify_vac_init_evidence_ed25519_signature;
pub use vac_init_evidence_chain::verify_evidence_record as verify_vac_init_evidence_record;
pub use vac_init_patch_guard::PatchAttempt as VacInitPatchAttempt;
pub use vac_init_patch_guard::PatchGuardContext as VacInitPatchGuardContext;
pub use vac_init_patch_guard::PatchGuardReport as VacInitPatchGuardReport;
pub use vac_init_patch_guard::validate_patch_attempt as validate_vac_init_patch_attempt;
pub use vac_init_policy_evaluator::ActionContext as VacInitActionContext;
pub use vac_init_policy_evaluator::PolicyDecision as VacInitPolicyEvaluationDecision;
pub use vac_init_policy_evaluator::PolicyEvaluationReport as VacInitPolicyEvaluationReport;
pub use vac_init_policy_evaluator::PolicyLayer as VacInitPolicyLayer;
pub use vac_init_policy_evaluator::PolicyRule as VacInitPolicyRule;
pub use vac_init_policy_evaluator::evaluate_policies as evaluate_vac_init_policies;
pub use vac_init_risk_policy::ConfidenceLabel as VacInitRiskConfidenceLabel;
pub use vac_init_risk_policy::PolicyInferenceReport as VacInitPolicyInferenceReport;
pub use vac_init_risk_policy::RiskAction as VacInitRiskAction;
pub use vac_init_risk_policy::RiskFinding as VacInitRiskFinding;
pub use vac_init_risk_policy::detect_risk_findings as detect_vac_init_risk_findings;
pub use vac_init_risk_policy::infer_policy_from_findings as infer_vac_init_policy_from_findings;
pub use vac_init_runtime_enforcement::CommandPolicyDecision as VacInitRuntimeCommandPolicyDecision;
pub use vac_init_runtime_enforcement::EvidenceCompletionGateContext as VacInitEvidenceCompletionGateContext;
pub use vac_init_runtime_enforcement::PreCommandGateContext as VacInitPreCommandGateContext;
pub use vac_init_runtime_enforcement::PrePatchGateContext as VacInitPrePatchGateContext;
pub use vac_init_runtime_enforcement::PrePlanGateContext as VacInitPrePlanGateContext;
pub use vac_init_runtime_enforcement::RuntimeCapabilityStatus as VacInitRuntimeCapabilityStatus;
pub use vac_init_runtime_enforcement::RuntimeEnforcementCoverage as VacInitRuntimeEnforcementCoverage;
pub use vac_init_runtime_enforcement::RuntimeGateDecision as VacInitRuntimeGateDecision;
pub use vac_init_runtime_enforcement::RuntimeGateIssue as VacInitRuntimeGateIssue;
pub use vac_init_runtime_enforcement::RuntimeGateKind as VacInitRuntimeGateKind;
pub use vac_init_runtime_enforcement::RuntimeGateReport as VacInitRuntimeGateReport;
pub use vac_init_runtime_enforcement::RuntimeOwnershipStatus as VacInitRuntimeOwnershipStatus;
pub use vac_init_runtime_enforcement::RuntimePlanTargetFile as VacInitRuntimePlanTargetFile;
pub use vac_init_runtime_enforcement::evaluate_evidence_completion_gate as evaluate_vac_init_evidence_completion_gate;
pub use vac_init_runtime_enforcement::evaluate_pre_command_gate as evaluate_vac_init_pre_command_gate;
pub use vac_init_runtime_enforcement::evaluate_pre_patch_gate as evaluate_vac_init_pre_patch_gate;
pub use vac_init_runtime_enforcement::evaluate_pre_plan_gate as evaluate_vac_init_pre_plan_gate;

pub use vac_init_runtime_bridge::RuntimeCommandContractReport as VacInitRuntimeCommandContractReport;
pub use vac_init_runtime_bridge::RuntimeEvidenceContractReport as VacInitRuntimeEvidenceContractReport;
pub use vac_init_runtime_bridge::RuntimePatchContractReport as VacInitRuntimePatchContractReport;
pub use vac_init_runtime_bridge::RuntimePatchFileChange as VacInitRuntimePatchFileChange;
pub use vac_init_runtime_bridge::evaluate_runtime_command_contract as evaluate_vac_init_runtime_command_contract;
pub use vac_init_runtime_bridge::evaluate_runtime_patch_contract as evaluate_vac_init_runtime_patch_contract;
pub use vac_init_runtime_bridge::lookup_safe_rationale_with_engine as lookup_vac_init_safe_rationale_with_engine;
pub use vac_init_runtime_bridge::preview_registry_migrations_with_engine as preview_vac_init_registry_migrations_with_engine;
pub use vac_init_runtime_bridge::runtime_command_enforcement_active as vac_init_runtime_command_enforcement_active;
pub use vac_init_runtime_bridge::validate_plan_yaml_with_engine as validate_vac_init_plan_yaml_with_engine;
pub use vac_init_runtime_bridge::write_runtime_command_evidence as write_vac_init_runtime_command_evidence;
pub use vac_init_runtime_bridge::write_runtime_patch_evidence as write_vac_init_runtime_patch_evidence;
pub use vac_init_semantic_plan::PlanValidationContext as VacInitPlanValidationContext;
pub use vac_init_semantic_plan::SemanticPlan as VacInitSemanticPlan;
pub use vac_init_semantic_plan::validate_semantic_plan as validate_vac_init_semantic_plan;

pub use completion_lock::CompletionLockDecision;
pub use completion_lock::CompletionLockOutcome;
pub use completion_lock::CompletionLockSummary;
pub use completion_lock::evaluate_completion_lock;
pub use completion_lock::session_close_state;
pub use no_duplicate_tui::NoDuplicateTuiFinding;
pub use no_duplicate_tui::NoDuplicateTuiReport;
pub use no_duplicate_tui::load_no_duplicate_tui_report;
pub use ownership_scan::OwnershipScanEntry;
pub use ownership_scan::OwnershipScanReport;
pub use ownership_scan::SourceInventoryEntry;
pub use ownership_scan::SourceInventoryReport;
pub use ownership_scan::UnownedSourceDomainEntry;
pub use ownership_scan::build_source_inventory_from_vac_root;
pub use ownership_scan::load_ownership_scan_report;
pub use policy_manifest::PolicyDecisionReport;
pub use policy_manifest::PolicyDoctorManifestEntry;
pub use policy_manifest::PolicyDoctorReport;
pub use policy_manifest::WorkflowStepExecutionIntent;
pub use policy_manifest::evaluate_step_policy;
pub use policy_manifest::load_policy_doctor_report;
pub use policy_registry::load_policy_doctor_report_for_path;
pub use registry::load_control_plane_registry_report;
pub use registry_diagnostics::RegistryDiagnostic;
pub use registry_diagnostics::RegistryDiagnosticSeverity;
pub use registry_diagnostics::RegistryLoadReport;
pub use registry_diagnostics::RegistryLoadState;
pub use root_feature_conversion::ConversionState;
pub use root_feature_conversion::RootFeatureConversionEntry;
pub use root_feature_conversion::RootFeatureConversionReport;
pub use root_feature_conversion::build_root_feature_conversion_report;
pub use session_artifacts::AcceptanceCriterion;
pub use session_artifacts::ArtifactContract;
pub use session_artifacts::SessionArtifactBundle;
pub use session_artifacts::SessionArtifactManifest;
pub use session_artifacts::SessionArtifactState;
pub use session_artifacts::SessionArtifactWriteResult;
pub use session_artifacts::SpecArtifact;
pub use session_artifacts::SpecArtifactState;
pub use session_artifacts::TaskArtifact;
pub use session_artifacts::TaskArtifactState;
pub use session_artifacts::TodoArtifact;
pub use session_artifacts::TodoArtifactState;
pub use session_artifacts::load_session_artifact_record;
pub use session_artifacts::load_session_bundle;
pub use session_artifacts::load_session_manifest;
pub use session_artifacts::read_session_artifact;
pub use session_artifacts::session_artifact_paths;
pub use session_artifacts::session_artifact_relative_path;
pub use session_artifacts::session_dir;
pub use session_artifacts::session_registry_dir;
pub use session_artifacts::validate_session_id;
pub use session_artifacts::write_session_artifacts;
pub use session_closeout::SessionCloseoutPaths;
pub use session_closeout::SessionCloseoutRecord;
pub use session_closeout::close_session_artifacts;
pub use session_closeout::session_closeout_paths;
pub use session_doctor::SessionDoctorReport;
pub use session_doctor::SessionDoctorSessionReport;
pub use session_doctor::load_session_doctor_report;
pub use slice_ledger::DuplicationCheck;
pub use slice_ledger::SliceLedgerEntry;
pub use slice_ledger::SliceLedgerIndex;
pub use slice_ledger::SliceLedgerIndexEntry;
pub use slice_ledger::SliceLedgerWriteResult;
pub use slice_ledger::append_slice_ledger_entry;
pub use slice_ledger::slice_ledger_entries_dir;
pub use slice_ledger::slice_ledger_entry_path;
pub use slice_ledger::slice_ledger_index_path;
pub use slice_ledger::slice_ledger_root;
pub use slice_ledger::validate_slice_id;
pub use surface_doctor::SurfaceDoctorManifestEntry;
pub use surface_doctor::SurfaceDoctorReport;
pub use surface_doctor::load_surface_doctor_report;
pub use surface_readiness::SurfaceRouteReadinessIssue;
pub use surface_readiness::SurfaceRouteReadinessReport;
pub use surface_readiness::load_surface_route_readiness_report;
pub use workflow_runner::WORKFLOW_STEP_POLICY_INTENTS;
pub use workflow_runner::WorkflowStepPolicyIntent;
pub use workflow_runner::evaluate_workflow_approval_policy;
pub use workflow_runner::load_workflow_run_report;
pub use workflow_runner::resolve_workflow_step_policy_intent;

pub use vac_init_doctor_release::DoctorAggregateReport;
pub use vac_init_doctor_release::DoctorCheckReport;
pub use vac_init_doctor_release::DoctorFinding;
pub use vac_init_doctor_release::DoctorKind;
pub use vac_init_doctor_release::DoctorSeverity;
pub use vac_init_doctor_release::DoctorStatus;
pub use vac_init_doctor_release::ReleaseGateContext;
pub use vac_init_doctor_release::aggregate_doctor_release;
pub use vac_init_doctor_release::validate_doctor_report;
pub use vac_init_durable_stores::ApprovalReplayBinding as VacInitDurableApprovalReplayBinding;
pub use vac_init_durable_stores::AtomicStoreWritePlan as VacInitAtomicStoreWritePlan;
pub use vac_init_durable_stores::DurableStoreKind as VacInitDurableStoreKind;
pub use vac_init_durable_stores::StoreEnvelope as VacInitStoreEnvelope;
pub use vac_init_fixture_security_regression::CargoGatePlan as VacInitCargoGatePlan;
pub use vac_init_fixture_security_regression::FixtureCategory as VacInitFixtureCategory;
pub use vac_init_fixture_security_regression::FixtureMatrixReport as VacInitFixtureMatrixReport;
pub use vac_init_fixture_security_regression::SecurityAttack as VacInitSecurityAttack;
pub use vac_init_fixture_security_regression::SecurityRegressionCase as VacInitSecurityRegressionCase;
pub use vac_init_fixture_security_regression::validate_security_regressions as validate_vac_init_security_regressions;
pub use vac_init_memory_governance::MemoryAccess;
pub use vac_init_memory_governance::MemoryContent;
pub use vac_init_memory_governance::MemoryContentType;
pub use vac_init_memory_governance::MemoryGovernanceError;
pub use vac_init_memory_governance::MemoryRecord;
pub use vac_init_memory_governance::MemorySource;
pub use vac_init_memory_governance::MemoryTier;
pub use vac_init_memory_governance::may_write_memory;
pub use vac_init_memory_governance::validate_memory_record;
pub use vac_init_migration_runtime::MigrationDryRunReport as VacInitMigrationDryRunReport;
pub use vac_init_migration_runtime::MigrationRecord as VacInitMigrationRecord;
pub use vac_init_migration_runtime::MigrationRuntimePlan as VacInitMigrationRuntimePlan;
pub use vac_init_migration_runtime::MigrationRuntimeRequest as VacInitMigrationRuntimeRequest;
pub use vac_init_migration_runtime::StructuredMigrationCommand as VacInitStructuredMigrationCommand;
pub use vac_init_migration_runtime::apply_migration_action_to_yaml_text as apply_vac_init_migration_action_to_yaml_text;
pub use vac_init_migration_runtime::build_migration_plan as build_vac_init_migration_plan;
pub use vac_init_migration_runtime::build_rollback_plan as build_vac_init_migration_rollback_plan;
pub use vac_init_migration_runtime::compatibility_kind_migration as vac_init_compatibility_kind_migration;
pub use vac_init_migration_runtime::preview_migration as preview_vac_init_migration;
pub use vac_init_migration_runtime::validate_migration_record_depth as validate_vac_init_migration_record_depth;
pub use vac_init_production_rc::DeterministicReadinessReport as VacInitDeterministicReadinessReport;
pub use vac_init_production_rc::E2eDryRunScenario as VacInitE2eDryRunScenario;
pub use vac_init_production_rc::MeasuredReadinessInput as VacInitMeasuredReadinessInput;
pub use vac_init_production_rc::ReleaseDoctorPass as VacInitReleaseDoctorPass;
pub use vac_init_safe_rationale::SafeApprovalRef;
pub use vac_init_safe_rationale::SafeChangesetExcerpt;
pub use vac_init_safe_rationale::SafeMemoryRef;
pub use vac_init_safe_rationale::SafeRationaleSummary;
pub use vac_init_safe_rationale::TrajectoryIndex;
pub use vac_init_safe_rationale::TrajectorySpan;
pub use vac_init_safe_rationale::WhyLookupReport;
pub use vac_init_safe_rationale::WhyQuery;
pub use vac_init_safe_rationale::WhyResult;
pub use vac_init_safe_rationale::lookup_safe_rationale;
pub use vac_init_safe_rationale::validate_safe_rationale;
pub use vac_init_scanner_policy_hardening::ScannerRiskFinding as VacInitScannerRiskFinding;
pub use vac_init_scanner_policy_hardening::SourceClass as VacInitSourceClass;
pub use vac_init_scanner_policy_hardening::classify_workspace_path as classify_vac_init_workspace_path;
pub use vac_init_scanner_policy_hardening::detect_rust_risk_pattern as detect_vac_init_rust_risk_pattern;
pub use vac_init_scanner_policy_hardening::infer_policy_decision as infer_vac_init_scanner_policy_decision;
pub use vac_init_tui_real_data::ApprovalPopupData as VacInitApprovalPopupData;
pub use vac_init_tui_real_data::AutopilotDoctorMonitorData as VacInitAutopilotDoctorMonitorData;
pub use vac_init_tui_real_data::CapabilityDashboardData as VacInitCapabilityDashboardData;
pub use vac_init_tui_real_data::load_approval_popup_data_from_store as load_vac_init_approval_popup_data_from_store;
pub use vac_init_tui_real_data::load_autopilot_doctor_monitor_from_workspace as load_vac_init_autopilot_doctor_monitor_from_workspace;
pub use vac_init_tui_real_data::load_capability_dashboard_data_from_workspace as load_vac_init_capability_dashboard_data_from_workspace;
