schema_version: 2
kind: merkle_root
id: anchor.1
epoch: 1
prev_epoch:
  id: null
  root_hash: null
leaves:
- capability: vac.init.evidence-chain
  head_id: evidence.vac.init.evidence-chain.1
  head_hash: ab70ef02b9d27ebd13d8c0c6c7aad029e9992ea78516bd76bdc10c87e44febf9
  head_seq: 1
root_hash: cdae522e6713be05f823c5c72a09d7c2c41e0085816ac6ad915aabada93fe383
trigger: manual
anchored_to:
  git_ref: refs/vac/anchors
  external:
    kind: none
    ref_id: null
broker_sig:
  algorithm: ed25519
  key_id: ed25519:O4OV/RClb6Y/U896oIS4eMuU8RvnKOZoDHvjYMMTeGM=
  value: 42EEPC1GKizzhWvrCLaP6wTxiL7POpw5eD+9ZhijPi/dErW3TAuVctmC0j98sNw+5uywafKu2lRbVCksfPg1Ag==
  mode: signed
