#!/usr/bin/env bash
set -euo pipefail
fail() { echo "control-plane audit findings static gate: $*" >&2; exit 1; }
scanner="vac-rs/crates/control-plane/control-plane/src/control_plane/vac_init_live_scanner_policy.rs"
autopilot="vac-rs/crates/control-plane/control-plane/src/control_plane/vac_init_autopilot_scheduler.rs"
operator_console="vac-rs/crates/surfaces/tui/src/operator_console.rs"
workflow="vac-rs/crates/surfaces/tui/src/workflow_browser.rs"
[[ -f "$scanner" ]] || fail "scanner module missing"
grep -q 'LIVE_SCANNER_METHOD: &str = RiskDetectionMethod::AstExact.as_str()' "$scanner" || fail "scanner must emit ast_exact"
grep -q 'fn rust_lexical_code' "$scanner" || fail "scanner must strip comments/strings before callsite matching"
! grep -q 'phase2_ast_exact: NotEvaluated' "$scanner" || fail "scanner still marks AST-exact NotEvaluated"
[[ -f "$autopilot" ]] || fail "autopilot scheduler runtime module missing"
grep -q 'refresh_autopilot_scheduler_status' "$autopilot" || fail "autopilot status writer missing"
grep -q 'execute_autopilot_action' "$autopilot" || fail "autopilot action executor missing"
grep -q 'execute_workflow_manifest_with_approval_policy' "$autopilot" || fail "autopilot scheduler must bind workflow_runner to approval policy"
grep -q 'AUTOPILOT_RUN_STATE_PATH' "$autopilot" || fail "autopilot scheduler must persist run-state for schedule dedupe"
grep -q 'workflow_is_due' "$autopilot" || fail "autopilot scheduler must guard against per-tick re-execution"
grep -q 'schedule_interval_secs' "$autopilot" || fail "autopilot scheduler must compute next-run intervals"
grep -q 'running' "$autopilot" || fail "autopilot scheduler must write a running lifecycle state before completion"
grep -q 'AUTOPILOT_RUN_LOG_PATH' "$autopilot" || fail "autopilot workflow execution log missing"
grep -q 'retry executed via workflow_runner' "$autopilot" || fail "autopilot retry must rerun the workflow executor"
! grep -q 'refresh_vac_init_autopilot_scheduler_status' vac-rs/crates/surfaces/tui/src/operator_ui.rs || fail "TUI runtime state loader must be read-only; render paths must not execute scheduler"
[[ -f "$operator_console" ]] || fail "persistent operator console view missing"
rg -q 'new_runtime_operator_console_view' vac-rs/crates/surfaces/tui/src/chatwidget || fail "/runtime must open operator console, not history-only output"
grep -q 'execute_vac_init_autopilot_action' "$operator_console" || fail "operator console job actions are inert"
grep -q 'KeyCode::Tab' "$operator_console" || fail "operator console must support tab navigation"
grep -q 'KeyCode::Right' "$operator_console" || fail "operator console must support right-arrow tab navigation"
grep -q 'pre_draw_tick' "$operator_console" || fail "operator console must expose a live tick hook"
grep -q 'refresh_view(false)' "$operator_console" || fail "operator console tick must be dirty-checked, not unconditional redraw"
grep -q 'current_view_signature' "$operator_console" || fail "operator console must compute dirty signatures before redraw"
grep -q 'file_signature' "$operator_console" || fail "operator console must poll persisted status files, not execute scheduler from draw"
! grep -q 'refresh_vac_init_autopilot_scheduler_status' "$operator_console" || fail "operator console draw path must not execute autopilot scheduler"
! grep -q 'fn refresh(&mut self)' "$operator_console" || fail "operator console must not keep unconditional refresh() hot path"
grep -q 'next_pre_draw_tick_delay' "$operator_console" || fail "operator console must schedule live refresh ticks"
grep -q 'execute_workflow_manifest' "$workflow" || fail "workflow browser must execute selected workflow on /workflow run"
grep -q 'runtime_profile_label' vac-rs/crates/surfaces/tui/src/operator_widget_render.rs || fail "status bar still lacks runtime profile/rulebook lookup"
grep -q 'MARKDOWN_RENDER_CACHE' vac-rs/crates/surfaces/tui/src/markdown_render.rs || fail "markdown renderer must memoize repeated renders"
[[ -f scripts/check-vac-source-artifact-packaging-gate.sh ]] || fail "artifact packaging gate missing"
bash scripts/check-vac-tui-operator-draw-readonly-contract.sh
bash scripts/check-vac-tui-local-tool-cleanup-static.sh
echo "control-plane audit findings static gate: PASS"
