#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"
fail() { echo "regen control-plane projection gate: $*" >&2; exit 1; }
for path in   scripts/regen-vac-control-plane-projection.py   .vac/.init/source_inventory.yaml   .vac/.init/scan_report.yaml   .vac/.init/risk_findings/index.yaml   .vac/.init/risk_findings/full.yaml   .vac/.init/policy_inference_report.yaml   .vac/.init/scanner_doctor_report.yaml   .vac/.init/state.yaml   docs/DOCS_INDEX_CURRENT.md   docs/PROJECT_STATE_CURRENT.md   docs/DOCS_AUDIT.md   docs/architecture/INDEX.md   .vac/registry/docs-state.yaml; do
  [[ -f "$path" ]] || fail "missing $path"
done
[[ ! -d docs/donor-migration ]] || fail "docs/donor-migration must remain pruned"
for protected in .vac/registry/evidence .vac/registry/plans .vac/registry/trajectory docs/architecture/adr docs/architecture/decisions; do
  [[ -d "$protected" ]] || fail "protected append-only bucket missing: $protected"
done
grep -q 'generator: scripts/regen-vac-control-plane-projection.py' .vac/.init/source_inventory.yaml || fail "source inventory not regenerated by canonical script"
grep -q 'protected_registry_history: preserved' .vac/.init/scanner_doctor_report.yaml || fail "scanner doctor missing protected history marker"
grep -q 'docs_pruned: true' .vac/registry/docs-state.yaml || fail "docs-state missing donor prune marker"
python3 - <<'PY'
from pathlib import Path
import re
recorded = re.search(r'markdown_files:\s*(\d+)', Path('.vac/registry/docs-state.yaml').read_text())
actual = len(list(Path('docs').rglob('*.md')))
if not recorded or int(recorded.group(1)) != actual:
    raise SystemExit(f'docs count drift recorded={recorded.group(1) if recorded else None} actual={actual}')
PY
printf 'regen control-plane projection gate: PASS
'
