#!/usr/bin/env bash
# Regenerate the rolling index for scheduled repo sentinel audit snapshots.
#
# The scheduled audit job writes timestamped *.md snapshots under
# docs/scheduled-audits/YYYY-MM-DD/. This script summarizes them into a stable
# docs/scheduled-audits/INDEX.md table for fast trend lookup.

set -euo pipefail

repo_root="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$repo_root"

audit_root="docs/scheduled-audits"
output="$audit_root/INDEX.md"

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

escape_cell() {
  local value="${1:-}"
  value="${value//$'\r'/ }"
  value="${value//$'\n'/ }"
  value="${value//|/\\|}"
  value="${value//</&lt;}"
  value="${value//>/&gt;}"
  printf '%s' "$value"
}

timestamp_for_file() {
  local file="$1"
  local heading
  heading="$(grep -m1 '^# Hourly Repo Sentinel Audit' "$file" || true)"
  if [[ "$heading" =~ ([0-9]{4}-[0-9]{2}-[0-9]{2})[[:space:]]+([0-9]{2}:[0-9]{2}) ]]; then
    printf '%s %s' "${BASH_REMATCH[1]}" "${BASH_REMATCH[2]}"
  else
    local date_part time_part base
    date_part="$(basename "$(dirname "$file")")"
    base="$(basename "$file")"
    time_part="${base%%-*}"
    if [[ "$date_part" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ && "$time_part" =~ ^[0-9]{4}$ ]]; then
      printf '%s %s:%s' "$date_part" "${time_part:0:2}" "${time_part:2:2}"
    else
      printf '%s' "$file"
    fi
  fi
}

overall_status_for_file() {
  local file="$1"
  if grep -Eq '^\|[[:space:]]*\*\*(CRITICAL|FAIL|ERROR)\*\*' "$file"; then
    printf 'FAIL'
  elif grep -Eq '^\|[[:space:]]*\*\*WARNING\*\*' "$file"; then
    printf 'WARNING'
  elif grep -Eq '^\|[[:space:]]*\*\*INFO\*\*' "$file"; then
    printf 'INFO'
  else
    printf 'PASS'
  fi
}

top_finding_for_file() {
  local file="$1"
  local line
  line="$(awk -F'|' '
    /^\|[[:space:]]*\*\*(CRITICAL|FAIL|ERROR|WARNING)\*\*/ { gsub(/^[[:space:]]+|[[:space:]]+$/, "", $4); print $4; exit }
  ' "$file")"
  if [ -z "$line" ]; then
    line="$(awk -F'|' '
      /^\|[[:space:]]*\*\*INFO\*\*/ { gsub(/^[[:space:]]+|[[:space:]]+$/, "", $4); print $4; exit }
    ' "$file")"
  fi
  if [ -z "$line" ]; then
    printf 'No findings table rows'
  else
    printf '%s' "$line" | sed -E 's/<br>.*$//; s/`//g; s/\*\*//g; s/[[:space:]]+/ /g'
  fi
}

plan_count_for_file() {
  local file="$1"
  grep -Ec '^### [0-9]+\.' "$file" || true
}

{
  echo '# Repository Sentinel Audit Index'
  echo
  echo 'Generated by `scripts/regenerate-audit-index.sh`. Historical snapshots are immutable point-in-time records; use this file only as a rolling summary.'
  echo
  echo '| Date/Time | Overall status | Top finding | Plan candidates count | File |'
  echo '|---|---|---|---:|---|'
} > "$tmp"

while IFS= read -r file; do
  timestamp="$(timestamp_for_file "$file")"
  status="$(overall_status_for_file "$file")"
  top="$(top_finding_for_file "$file")"
  plans="$(plan_count_for_file "$file")"
  printf '| %s | %s | %s | %s | [%s](%s) |\n' \
    "$(escape_cell "$timestamp")" \
    "$(escape_cell "$status")" \
    "$(escape_cell "$top")" \
    "$(escape_cell "$plans")" \
    "$(escape_cell "$file")" \
    "$(escape_cell "${file#docs/scheduled-audits/}")" >> "$tmp"
done < <(find "$audit_root" -mindepth 2 -type f -name '*.md' | sort -r)

mv "$tmp" "$output"
